### PR TITLE
[MRG]: FIX Quicksort + Cache friendly PresortBestSplitter

### PR DESCRIPTION
**Pull request by glouppe**

### CODE REVIEW

**Comment by glouppe** [comment]
Feel free to merge this in. I won't make any more change.

**Comment by larsmans** [comment]
Wow, thanks! I'm not sure if deleting the heapsort is a good idea at this point, as we might want to back off to it.

**Comment by glouppe** [comment]
> I'm not sure if deleting the heapsort is a good idea at this point, as we might want to back off to it.

Indeed, this may still be useful for our benchmarks. I amended my last commit and put heapsort back in.

**Comment by pprett** [comment]
@larsmans can you merge this one in the original PR? or do you have any concerns?

**Comment by larsmans** [comment]
No concerns, just little time. I don't get paid to hack on scikit-learn.

**Pull request merged**
